"""Alembic environment.

Runs synchronously against ALEMBIC_DATABASE_URL (psycopg driver). The app uses
asyncpg; migrations do not need the async stack and are simpler without it.

The URL is handed straight to create_engine rather than through
`config.set_main_option`. That setter writes into ConfigParser, which applies
`%`-interpolation and rejects any percent-encoded character — a URL-encoded
password (`%40` for `@`) raises "invalid interpolation syntax" and, under the
console-script wrapper, does it while still exiting 0. Keeping the URL out of
ConfigParser removes the whole class of failure.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import create_engine, pool

from alembic import context
from app.config import settings

# Importing the models registers them on Base.metadata for autogenerate.
from app.core import models  # noqa: F401
from app.db import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# PostGIS and pgvector own objects in the same schema as our tables on this
# deployment (Supabase installs both into `public`). Without these filters every
# autogenerated revision proposes dropping PostGIS's own catalog tables.
EXTENSION_TABLES = {
    "spatial_ref_sys",
    "geography_columns",
    "geometry_columns",
    "raster_columns",
    "raster_overviews",
}


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep extension-owned objects out of autogenerate.

    Three separate hazards:

    1. PostGIS catalog tables (above) are not ours to manage.
    2. geoalchemy2 emits its own spatial index DDL as a side effect of defining
       a Geography column, so a reflected spatial index has no counterpart in
       the metadata and alembic proposes dropping it every run.
    3. pgvector's HNSW index is created by hand in the migration, for the same
       reason — the operator class is not expressible in plain Index() metadata.
    """
    if type_ == "table" and name in EXTENSION_TABLES:
        return False

    if type_ == "index" and reflected and compare_to is None:
        # A reflected index with nothing to compare against is either PostGIS's,
        # geoalchemy2's, or one we created by hand in a migration. Dropping it
        # is never what we meant.
        if name and (name.startswith("idx_") or name.startswith("ix_hnsw_")):
            return False

    return True


def run_migrations_offline() -> None:
    context.configure(
        url=settings.alembic_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(settings.alembic_database_url, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
