"""initial schema

Revision ID: 0002_initial_schema
Revises: 0001_extensions
Create Date: 2026-08-30 16:18:13.922670
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002_initial_schema'
down_revision: str | None = '0001_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'agronomist', 'official', name='role'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'farmer' AND phone IS NOT NULL AND password_hash IS NULL) OR (role IN ('agronomist','official') AND email IS NOT NULL AND password_hash IS NOT NULL)", name='ck_app_user_role_credentials'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('corpus_doc',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reviewed_on', sa.Date(), nullable=True),
    sa.Column('target', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=True),
    sa.Column('crop', sa.Enum('paddy', name='crop'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corpus_doc_crop_target', 'corpus_doc', ['crop', 'target'], unique=False)
    op.create_table('label_prior',
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('crop', sa.Enum('paddy', name='crop'), nullable=False),
    sa.Column('growth_stage', sa.Enum('nursery', 'tillering', 'vegetative', 'booting', 'flowering', 'maturity', name='growth_stage'), nullable=False),
    sa.Column('label', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('corrected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confirmed_count >= 0 AND corrected_count >= 0', name='ck_label_prior_counts_non_negative'),
    sa.PrimaryKeyConstraint('region', 'crop', 'growth_stage', 'label')
    )
    op.create_table('otp_request',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_otp_request_attempts_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_request_phone'), 'otp_request', ['phone'], unique=False)
    op.create_table('registered_use',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('active_ingredient', sa.Text(), nullable=False),
    sa.Column('crop', sa.Enum('paddy', name='crop'), nullable=False),
    sa.Column('target', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=False),
    sa.Column('pesticide_class', sa.Text(), nullable=False),
    sa.Column('dosage_text', sa.Text(), nullable=False),
    sa.Column('phi_days', sa.Integer(), nullable=False),
    sa.Column('reentry_hours', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.CheckConstraint("pesticide_class IN ('fungicide','insecticide','herbicide','acaricide','nematicide','other')", name='ck_registered_use_pesticide_class'),
    sa.CheckConstraint('phi_days >= 0', name='ck_registered_use_phi_days_non_negative'),
    sa.CheckConstraint('reentry_hours >= 0', name='ck_registered_use_reentry_hours_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_ingredient', 'crop', 'target', name='uq_registered_use_ingredient_crop_target')
    )
    op.create_index(op.f('ix_registered_use_active_ingredient'), 'registered_use', ['active_ingredient'], unique=False)
    op.create_index('ix_registered_use_lookup', 'registered_use', ['active_ingredient', 'crop'], unique=False)
    op.create_table('distinguishing_cue',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cue_text', sa.Text(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('discriminates', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('answer_yes_implies', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(discriminates, 1) = 2', name='ck_distinguishing_cue_pair'),
    sa.ForeignKeyConstraint(['doc_id'], ['corpus_doc.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.Enum('paddy', name='crop'), nullable=False),
    sa.Column('variety', sa.Text(), nullable=True),
    sa.Column('growth_stage', sa.Enum('nursery', 'tillering', 'vegetative', 'booting', 'flowering', 'maturity', name='growth_stage'), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False, spatial_index=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farm_location', 'farm', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_farm_farmer_id'), 'farm', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farm_region'), 'farm', ['region'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('weather', 'seasonal', 'spread', 'combined', name='alert_trigger'), nullable=False),
    sa.Column('target', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'moderate', 'high', name='risk_level'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('inspection_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.Enum('nothing_found', 'found', 'snoozed', name='alert_outcome'), nullable=True),
    sa.CheckConstraint('jsonb_array_length(inspection_tasks) > 0', name='ck_alert_inspection_tasks_non_empty'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_farm_id'), 'alert', ['farm_id'], unique=False)
    op.create_index('ix_alert_farm_outcome', 'alert', ['farm_id', 'outcome'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('image', 'audio', name='asset_kind'), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('byte_size IS NULL OR byte_size >= 0', name='ck_asset_byte_size'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_asset_farm_id'), 'asset', ['farm_id'], unique=False)
    op.create_table('problem',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('problem_type', sa.Enum('disease', 'pest', name='problem_type'), nullable=False),
    sa.Column('label', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=True),
    sa.Column('severity', sa.Enum('early', 'moderate', 'severe', name='problem_severity'), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='problem_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'resolved') = (resolved_at IS NOT NULL)", name='ck_problem_resolved_at_matches_status'),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_farm_id'), 'problem', ['farm_id'], unique=False)
    op.create_index('ix_problem_farm_status', 'problem', ['farm_id', 'status'], unique=False)
    op.create_table('advisory',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('possible_issue', sa.Text(), nullable=False),
    sa.Column('what_to_check', sa.Text(), nullable=False),
    sa.Column('what_to_avoid', sa.Text(), nullable=False),
    sa.Column('ladder', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expert_trigger', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(ladder) = 'array'", name='ck_advisory_ladder_is_array'),
    sa.CheckConstraint('NOT (ladder @> \'[{"tier":"chemical"}]\'::jsonb) OR (ladder -> -1 ->> \'tier\' = \'chemical\')', name='ck_advisory_ladder_chemical_last'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_problem_id'), 'advisory', ['problem_id'], unique=False)
    op.create_table('case',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'assigned', 'resolved', name='case_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_assigned_to'), 'case', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_case_problem_id'), 'case', ['problem_id'], unique=False)
    op.create_table('diagnosis',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('topk', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_outcome', sa.Enum('advise', 'clarify', 'escalate', name='gate_outcome'), nullable=False),
    sa.Column('gate_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reason_code', sa.Enum('ABOVE_GATE', 'AMBIGUOUS', 'BELOW_FLOOR', 'OUT_OF_SCOPE', 'NO_RELEVANT_SOURCE', name='gate_reason_code'), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('is_stub', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gate_confidence >= 0 AND gate_confidence <= 1', name='ck_diagnosis_confidence_is_a_probability'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_problem_id'), 'diagnosis', ['problem_id'], unique=False)
    op.create_table('follow_up',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response', sa.Enum('improved', 'no_change', 'got_worse', name='followup_response'), nullable=True),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(response IS NULL) = (responded_at IS NULL)', name='ck_follow_up_response_and_timestamp_agree'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_due_at'), 'follow_up', ['due_at'], unique=False)
    op.create_index(op.f('ix_follow_up_problem_id'), 'follow_up', ['problem_id'], unique=False)
    op.create_table('label_check',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verdict_code', sa.Enum('NO_OBJECTION_FOUND', 'NOT_REGISTERED_FOR_TARGET', 'WRONG_CROP', 'WRONG_CLASS', 'PHI_CONFLICT', 'NOT_IN_RECORDS', name='verdict_code'), nullable=True),
    sa.Column('matched_row_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ocr_confidence IS NULL OR (ocr_confidence >= 0 AND ocr_confidence <= 1)', name='ck_label_check_ocr_confidence_is_a_probability'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_row_id'], ['registered_use.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_check_problem_id'), 'label_check', ['problem_id'], unique=False)
    op.create_table('label_reference',
    sa.Column('label', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('observation',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('doubt_doctor', 'field_note', name='observation_kind'), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Enum('yes', 'no', 'unknown', name='cue_answer'), nullable=True),
    sa.Column('cue_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cue_id'], ['distinguishing_cue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_problem_id'), 'observation', ['problem_id'], unique=False)
    op.create_table('confirmation',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('agronomist_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.Enum('confirmed', 'corrected', name='confirmation_verdict'), nullable=False),
    sa.Column('corrected_label', sa.Enum('blast', 'brown_spot', 'bacterial_leaf_blight', 'yellow_stem_borer', 'brown_planthopper', name='target_label'), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verdict = 'corrected') = (corrected_label IS NOT NULL)", name='ck_confirmation_corrected_requires_label'),
    sa.ForeignKeyConstraint(['agronomist_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmation_case_id'), 'confirmation', ['case_id'], unique=False)
    op.create_index(op.f('ix_confirmation_problem_id'), 'confirmation', ['problem_id'], unique=False)
    # pgvector HNSW index for cosine distance. Hand-written: the vector operator
    # class is not expressible in Index() metadata, so autogenerate cannot emit it.
    op.execute(
        "CREATE INDEX ix_hnsw_corpus_doc_embedding ON corpus_doc "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_hnsw_corpus_doc_embedding")
    op.drop_index(op.f('ix_confirmation_problem_id'), table_name='confirmation')
    op.drop_index(op.f('ix_confirmation_case_id'), table_name='confirmation')
    op.drop_table('confirmation')
    op.drop_index(op.f('ix_observation_problem_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_table('label_reference')
    op.drop_index(op.f('ix_label_check_problem_id'), table_name='label_check')
    op.drop_table('label_check')
    op.drop_index(op.f('ix_follow_up_problem_id'), table_name='follow_up')
    op.drop_index(op.f('ix_follow_up_due_at'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_diagnosis_problem_id'), table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index(op.f('ix_case_problem_id'), table_name='case')
    op.drop_index(op.f('ix_case_assigned_to'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_advisory_problem_id'), table_name='advisory')
    op.drop_table('advisory')
    op.drop_index('ix_problem_farm_status', table_name='problem')
    op.drop_index(op.f('ix_problem_farm_id'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_asset_farm_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index('ix_alert_farm_outcome', table_name='alert')
    op.drop_index(op.f('ix_alert_farm_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_farm_region'), table_name='farm')
    op.drop_index(op.f('ix_farm_farmer_id'), table_name='farm')
    op.drop_index('idx_farm_location', table_name='farm', postgresql_using='gist')
    op.drop_table('farm')
    op.drop_table('distinguishing_cue')
    op.drop_index('ix_registered_use_lookup', table_name='registered_use')
    op.drop_index(op.f('ix_registered_use_active_ingredient'), table_name='registered_use')
    op.drop_table('registered_use')
    op.drop_index(op.f('ix_otp_request_phone'), table_name='otp_request')
    op.drop_table('otp_request')
    op.drop_table('label_prior')
    op.drop_index('ix_corpus_doc_crop_target', table_name='corpus_doc')
    op.drop_table('corpus_doc')
    op.drop_table('app_user')

    # Postgres does not drop an enum type when the last table using it is
    # dropped. Without these, downgrade -1 followed by upgrade head fails on
    # "type already exists" — so the migration would not be reversible.
    op.execute("DROP TYPE IF EXISTS alert_outcome")
    op.execute("DROP TYPE IF EXISTS alert_trigger")
    op.execute("DROP TYPE IF EXISTS asset_kind")
    op.execute("DROP TYPE IF EXISTS case_status")
    op.execute("DROP TYPE IF EXISTS confirmation_verdict")
    op.execute("DROP TYPE IF EXISTS crop")
    op.execute("DROP TYPE IF EXISTS cue_answer")
    op.execute("DROP TYPE IF EXISTS followup_response")
    op.execute("DROP TYPE IF EXISTS gate_outcome")
    op.execute("DROP TYPE IF EXISTS gate_reason_code")
    op.execute("DROP TYPE IF EXISTS growth_stage")
    op.execute("DROP TYPE IF EXISTS observation_kind")
    op.execute("DROP TYPE IF EXISTS problem_severity")
    op.execute("DROP TYPE IF EXISTS problem_status")
    op.execute("DROP TYPE IF EXISTS problem_type")
    op.execute("DROP TYPE IF EXISTS risk_level")
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("DROP TYPE IF EXISTS target_label")
    op.execute("DROP TYPE IF EXISTS verdict_code")
    # ### end Alembic commands ###
