"""farm sowing_date

Revision ID: 0003_farm_sowing_date
Revises: 0002_initial_schema
Create Date: 2026-08-30 16:50:31.687493
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0003_farm_sowing_date'
down_revision: str | None = '0002_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('sowing_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'sowing_date')
    # ### end Alembic commands ###
